ALTER TABLE public.newsletter_subscribers
  ADD COLUMN IF NOT EXISTS metadata jsonb DEFAULT '{}'::jsonb;

ALTER TABLE public.abandoned_carts
  ADD COLUMN IF NOT EXISTS last_seen_at timestamptz,
  ADD COLUMN IF NOT EXISTS metadata jsonb DEFAULT '{}'::jsonb;

ALTER TABLE public.glowmia_orders
  ADD COLUMN IF NOT EXISTS email text;

ALTER TABLE public.glowmia_saved_designs
  ADD COLUMN IF NOT EXISTS email text;

CREATE TABLE IF NOT EXISTS public.email_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email text NOT NULL,
  event_type text NOT NULL,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);
